apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cron
spec:
  #Run every fifth hour
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
     template:
       spec:
         containers:
         - name: batch-job
           image: my-batch-image
         restartPolicy: OnFailure
