apiVersion: v1
kind: Pod
metadata:
  name: volumepod
spec:
  volumes:
    - name: "node-data"
      hostPath:
        path: "/var/lib/node"
  containers:
    - image: preet2fun/simple-node:v1
      name: example-container
      volumeMounts:
         - mountPath: "/data"
           name: "node-data"
