apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - image: preet2fun/node-sample:v1
      name: example-container
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
