apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"resource-example","namespace":"default"},"spec":{"containers":[{"image":"preet2fun/simple-node:v1","name":"simple-node","resources":{"limits":{"cpu":"250m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"56Mi"}}}]}}
  creationTimestamp: "2020-08-16T04:49:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.40.0.3"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-08-16T04:49:51Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:containers:
          k:{"name":"simple-node"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl
    operation: Update
    time: "2020-08-16T05:00:47Z"
  name: resource-example
  namespace: default
  resourceVersion: "5536725"
  selfLink: /api/v1/namespaces/default/pods/resource-example
  uid: 0760a9d6-c9c6-443d-bca2-12b285e3af50
spec:
  volumes:
    - name: "vol-data"
      hostPath:
        path: "/var/lib/volumetest"

  containers:
  - image: preet2fun/simple-node:v1
    imagePullPolicy: IfNotPresent
    name: simple-node
    volumeMounts:
        - mountPath: "/data"
          name: "vol-data"
    resources:
      requests:
        cpu: 100m
        memory: 56Mi
      limits:
        cpu: 200m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-mtj67
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-mtj67
    secret:
      defaultMode: 420
      secretName: default-token-mtj67
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-16T04:49:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-16T04:49:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-16T04:49:51Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-16T04:49:49Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7654e9aab343fa8c6c4724790ec9eb822c8d53577e6457e188482e200bf4956a
    image: preet2fun/simple-node:v1
    imageID: docker-pullable://preet2fun/simple-node@sha256:ff3dd705419da87dda41b97e035e1cce12cd45a25a141e49f08ef441e1201c18
    lastState: {}
    name: simple-node
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-16T04:49:50Z"
  hostIP: 172.16.8.242
  phase: Running
  podIP: 10.40.0.3
  podIPs:
  - ip: 10.40.0.3
  qosClass: Burstable
  startTime: "2020-08-16T04:49:49Z"
