apiVersion: v1
kind: Pod
metadata:
  name: resource-example
spec:
  containers:
    - image: preet2fun/simple-node:v1
      name: simple-node
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"

